//BSD  2014 ,WinterCore 
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;

using HtmlRenderer.Dom;
namespace HtmlRenderer.WebDom
{
    public enum WellknownCssPropertyName
    {
        Unknown,

        [CssName("display")]
        Display,

        [CssName("border")]
        Border,
        [CssName("border-left")]
        BorderLeft,
        [CssName("border-right")]
        BorderRight,
        [CssName("border-bottom")]
        BorderBottom,
        [CssName("border-top")]
        BorderTop,
        //----------------------------------
        [CssName("border-width")]
        BorderWidth,
        [CssName("border-bottom-width")]
        BorderBottomWidth,
        [CssName("border-left-width")]
        BorderLeftWidth,
        [CssName("border-top-width")]
        BorderTopWidth,
        [CssName("border-right-width")]
        BorderRightWidth,
        //----------------------------------
        [CssName("border-style")]
        BorderStyle,
        [CssName("border-bottom-style")]
        BorderBottomStyle,
        [CssName("border-left-style")]
        BorderLeftStyle,
        [CssName("border-top-style")]
        BorderTopStyle,
        [CssName("border-right-style")]
        BorderRightStyle,
        //----------------------------------
        [CssName("border-color")]
        BorderColor,
        [CssName("border-bottom-color")]
        BorderBottomColor,
        [CssName("border-left-color")]
        BorderLeftColor,
        [CssName("border-top-color")]
        BorderTopColor,
        [CssName("border-right-color")]
        BorderRightColor,
        //----------------------------------
        [CssName("border-spacing")]
        BorderSpacing,
        [CssName("border-collapse")]
        BorderCollapse,
        //----------------------------------
        [CssName("corner-radius")]
        CornerRadius,
        [CssName("corner-nw-radius")]
        CornerNWRadius,
        [CssName("corner-ne-radius")]
        CornerNERadius,
        [CssName("corner-sw-radius")]
        CornerSWRadius,
        [CssName("corner-se-radius")]
        CornerSERadius,
        //----------------------------------
        [CssName("margin")]
        Margin,
        [CssName("margin-bottom")]
        MarginBottom,
        [CssName("margin-top")]
        MarginTop,
        [CssName("margin-left")]
        MarginLeft,
        [CssName("margin-right")]
        MarginRight,
        //----------------------------------
        [CssName("padding")]
        Padding,
        [CssName("padding-bottom")]
        PaddingBottom,
        [CssName("padding-top")]
        PaddingTop,
        [CssName("padding-left")]
        PaddingLeft,
        [CssName("padding-right")]
        PaddingRight,
        //----------------------------------
        [CssName("left")]
        Left,
        [CssName("top")]
        Top,
        [CssName("width")]
        Width,
        [CssName("max-width")]
        MaxWidth,
        [CssName("height")]
        Height,
        //----------------------------------
        [CssName("background-color")]
        BackgroundColor,
        [CssName("background-image")]
        BackgroundImage,
        [CssName("background-position")]
        BackgroundPosition,
        [CssName("background-gradient")]
        BackgroundGradient,
        [CssName("background-gradient-angle")]
        BackgroundGradientAngle,
        [CssName("background-angle")]
        BackgroundAngle,
        [CssName("background-repeat")]
        BackgroundRepeat,
        //----------------------------------
        [CssName("color")]
        Color,
        [CssName("direction")]
        Direction,
        [CssName("empty-cells")]
        EmptyCells,
        [CssName("float")]
        Float,
        [CssName("position")]
        Position,
        [CssName("line-height")]
        LineHeight,
        [CssName("vertical-align")]
        VerticalAlign,
        [CssName("text-indent")]
        TextIndent,
        [CssName("text-align")]
        TextAlign,
        [CssName("text-decoration")]
        TextDecoration,

        [CssName("white-space")]
        Whitespace,
        [CssName("word-break")]
        WordBreak,
        [CssName("word-spacing")]
        WordSpacing,
        [CssName("visibility")]
        Visibility,
        [CssName("font")]
        Font,
        [CssName("font-family")]
        FontFamily,
        [CssName("font-size")]
        FontSize,
        [CssName("font-style")]
        FontStyle,
        [CssName("font-variant")]
        FontVariant,
        [CssName("font-weight")]
        FontWeight,

        [CssName("list-style")]
        ListStyle,
        [CssName("list-style-position")]
        ListStylePosition,
        [CssName("list-style-image")]
        ListStyleImage,
        [CssName("list-style-type")]
        ListStyleType,

        [CssName("overflow")]
        Overflow,
        //----------------------------------
        [CssName("content")]
        Content,
        //----------------------------------
        [CssName("outline")]
        Outline,
        [CssName("unicode-bidi")]
        UnicodeBidi,
        [CssName("page-break-before")]
        PageBreakBefore,
        [CssName("page-break-after")]
        PageBreakAfter
    }

}